-- Email generation stored procedure
CREATE OR REPLACE PROCEDURE __DATABASE__.__SCHEMA__.GENERATE_INSPECTION_EMAIL()
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.9'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'generate_email'
EXECUTE AS CALLER
AS
$$
import json

def generate_email(session):
    inspections = session.sql("""
        SELECT INSPECTION_ID, INSPECTION_NUM, COMPANY, FLEET, UNIT_NUM, SERIAL_NUM,
               MODEL_NUM, LOCATION, INSPECTOR, ORDER_DATE, COMPLETE_DATE, STATUS,
               TROUBLE_TICKET, INVOICE_NUM
        FROM __DATABASE__.__SCHEMA__.INSPECTION_SUMMARY
        WHERE EMAIL_SENT_AT IS NULL
        ORDER BY INSPECTION_NUM
    """).collect()

    if not inspections:
        return 'No new inspections to email'

    html_parts = []
    html_parts.append("""
    <html><body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333; border-bottom: 2px solid #0066cc; padding-bottom: 10px;">
        Vehicle Inspection Report</h1>
    """)

    inspection_nums = []
    inspection_ids = []

    for insp in inspections:
        insp_id = insp['INSPECTION_ID']
        insp_num = insp['INSPECTION_NUM'] or 'N/A'
        inspection_nums.append(str(insp_num))
        inspection_ids.append(insp_id)

        html_parts.append(f"""
        <div style="background: #f5f5f5; border: 1px solid #ddd; border-radius: 5px; padding: 15px; margin: 20px 0;">
            <h2 style="color: #0066cc; margin-top: 0;">Inspection #{insp_num}</h2>
            <table style="width: 100%; border-collapse: collapse;">
                <tr><td style="padding: 4px 8px;"><strong>Company:</strong> {insp['COMPANY'] or 'N/A'}</td>
                    <td style="padding: 4px 8px;"><strong>Fleet:</strong> {insp['FLEET'] or 'N/A'}</td></tr>
                <tr><td style="padding: 4px 8px;"><strong>Unit #:</strong> {insp['UNIT_NUM'] or 'N/A'}</td>
                    <td style="padding: 4px 8px;"><strong>Serial #:</strong> {insp['SERIAL_NUM'] or 'N/A'}</td></tr>
                <tr><td style="padding: 4px 8px;"><strong>Inspector:</strong> {insp['INSPECTOR'] or 'N/A'}</td>
                    <td style="padding: 4px 8px;"><strong>Status:</strong> {insp['STATUS'] or 'N/A'}</td></tr>
                <tr><td style="padding: 4px 8px;"><strong>Order Date:</strong> {insp['ORDER_DATE'] or 'N/A'}</td>
                    <td style="padding: 4px 8px;"><strong>Complete Date:</strong> {insp['COMPLETE_DATE'] or 'N/A'}</td></tr>
            </table>
        </div>
        """)

        failed_items = session.sql(f"""
            SELECT ITEM_ID, LINE_NUM, DESCRIPTION, COMMENTS
            FROM __DATABASE__.__SCHEMA__.FAILED_LINE_ITEMS
            WHERE INSPECTION_ID = '{insp_id}' ORDER BY LINE_NUM
        """).collect()

        if failed_items:
            html_parts.append('<h3 style="color: #cc3300;">Failed Items</h3>')
            for item in failed_items:
                html_parts.append(f"""
                <div style="border-left: 4px solid #cc3300; padding: 10px 15px; margin: 10px 0; background: #fff5f5;">
                    <strong>{item['LINE_NUM']} - {item['DESCRIPTION']}</strong>
                """)
                if item['COMMENTS']:
                    html_parts.append(f'<p style="margin: 5px 0; color: #555;">{item["COMMENTS"]}</p>')

                images = session.sql(f"""
                    SELECT GET_PRESIGNED_URL(@__DATABASE__.__SCHEMA__.INSPECTION_IMAGES, STAGE_PATH, 604800) as IMG_URL
                    FROM __DATABASE__.__SCHEMA__.FAILURE_IMAGES
                    WHERE ITEM_ID = '{item["ITEM_ID"]}' ORDER BY IMAGE_SEQUENCE
                """).collect()

                if images:
                    html_parts.append('<div style="margin-top: 8px;">')
                    for img in images:
                        html_parts.append(f'<img src="{img["IMG_URL"]}" style="max-width: 300px; max-height: 250px; margin: 5px; border: 1px solid #ddd; border-radius: 3px;">')
                    html_parts.append('</div>')
                html_parts.append('</div>')

        html_parts.append('<hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">')

    html_parts.append('<p style="color: #888; font-size: 12px;">Generated by Vehicle Inspection Pipeline | Images valid for 7 days</p></body></html>')
    html_body = ''.join(html_parts)

    if len(inspection_nums) == 1:
        subject = f"Vehicle Inspection Report - Inspection #{inspection_nums[0]}"
    else:
        subject = f"Vehicle Inspection Report - {len(inspection_nums)} Inspections"

    html_escaped = html_body.replace("'", "''")
    session.sql(f"""
        CALL SYSTEM$SEND_SNOWFLAKE_NOTIFICATION(
            SNOWFLAKE.NOTIFICATION.TEXT_HTML('{html_escaped}'),
            SNOWFLAKE.NOTIFICATION.EMAIL_INTEGRATION_CONFIG(
                'INSPECTION_EMAIL_INT', '{subject}',
                ARRAY_CONSTRUCT('__EMAIL__')
            )
        )
    """).collect()

    ids_list = "','".join(inspection_ids)
    session.sql(f"""
        UPDATE __DATABASE__.__SCHEMA__.INSPECTION_SUMMARY
        SET EMAIL_SENT_AT = CURRENT_TIMESTAMP()
        WHERE INSPECTION_ID IN ('{ids_list}')
    """).collect()

    return f"Email sent for {len(inspection_nums)} inspection(s): #{', #'.join(inspection_nums)}"
$$;
